// Сгенерировано scripts/gen-emoji-svg.mjs — не редактировать руками.
// Индекс Minecraft-совместимых эмодзи. SVG лежат в public/emoji и раздаются
// Vite как статика: путь в `file` — URL от корня приложения.

export type EmojiTier = "native" | "extra" | "text";

export interface McEmoji {
/** Символ для вставки в чат Minecraft. */
char: string;
/** Путь к SVG (URL от корня, раздаётся из public/emoji). */
file: string;
/** native — 44 эмодзи, рисуемых самим Mojangles; extra — остальной gist; text — фолбэк. */
tier: EmojiTier;
}

export const MC_EMOJI: Record<string, McEmoji> = {
  "smiling-face": { char: "☺", file: "emoji/emoji-smiling-face.svg", tier: "native" },
  "frowning-face": { char: "☹", file: "emoji/emoji-frowning-face.svg", tier: "native" },
  "skull-and-crossbones": { char: "☠", file: "emoji/emoji-skull-and-crossbones.svg", tier: "native" },
  "heart-exclamation": { char: "❣", file: "emoji/emoji-heart-exclamation.svg", tier: "native" },
  "red-heart": { char: "❤", file: "emoji/emoji-red-heart.svg", tier: "native" },
  "victory-hand": { char: "✌", file: "emoji/emoji-victory-hand.svg", tier: "extra" },
  "index-pointing-up": { char: "☝", file: "emoji/emoji-index-pointing-up.svg", tier: "extra" },
  "writing-hand": { char: "✍", file: "emoji/emoji-writing-hand.svg", tier: "extra" },
  "hot-springs": { char: "♨", file: "emoji/emoji-hot-springs.svg", tier: "extra" },
  "airplane": { char: "✈", file: "emoji/emoji-airplane.svg", tier: "extra" },
  "hourglass-done": { char: "⌛", file: "emoji/emoji-hourglass-done.svg", tier: "extra" },
  "watch": { char: "⌚", file: "emoji/emoji-watch.svg", tier: "extra" },
  "sun": { char: "☀", file: "emoji/emoji-sun.svg", tier: "native" },
  "cloud": { char: "☁", file: "emoji/emoji-cloud.svg", tier: "native" },
  "umbrella": { char: "☂", file: "emoji/emoji-umbrella.svg", tier: "native" },
  "snowflake": { char: "❄", file: "emoji/emoji-snowflake.svg", tier: "native" },
  "snowman": { char: "☃", file: "emoji/emoji-snowman.svg", tier: "native" },
  "comet": { char: "☄", file: "emoji/emoji-comet.svg", tier: "native" },
  "spade-suit": { char: "♠", file: "emoji/emoji-spade-suit.svg", tier: "native" },
  "heart-suit": { char: "♥", file: "emoji/emoji-heart-suit.svg", tier: "native" },
  "diamond-suit": { char: "♦", file: "emoji/emoji-diamond-suit.svg", tier: "native" },
  "club-suit": { char: "♣", file: "emoji/emoji-club-suit.svg", tier: "native" },
  "chess-pawn": { char: "♟", file: "emoji/emoji-chess-pawn.svg", tier: "extra" },
  "telephone": { char: "☎", file: "emoji/emoji-telephone.svg", tier: "extra" },
  "keyboard": { char: "⌨", file: "emoji/emoji-keyboard.svg", tier: "extra" },
  "envelope": { char: "✉", file: "emoji/emoji-envelope.svg", tier: "native" },
  "pencil": { char: "✏", file: "emoji/emoji-pencil.svg", tier: "extra" },
  "black-nib": { char: "✒", file: "emoji/emoji-black-nib.svg", tier: "extra" },
  "scissors": { char: "✂", file: "emoji/emoji-scissors.svg", tier: "native" },
  "radioactive": { char: "☢", file: "emoji/emoji-radioactive.svg", tier: "extra" },
  "biohazard": { char: "☣", file: "emoji/emoji-biohazard.svg", tier: "extra" },
  "up-arrow": { char: "⬆", file: "emoji/emoji-up-arrow.svg", tier: "extra" },
  "down-arrow": { char: "⬇", file: "emoji/emoji-down-arrow.svg", tier: "extra" },
  "right-arrow": { char: "➡", file: "emoji/emoji-right-arrow.svg", tier: "extra" },
  "left-arrow": { char: "⬅", file: "emoji/emoji-left-arrow.svg", tier: "extra" },
  "up-right-arrow": { char: "↗", file: "emoji/emoji-up-right-arrow.svg", tier: "extra" },
  "down-right-arrow": { char: "↘", file: "emoji/emoji-down-right-arrow.svg", tier: "extra" },
  "down-left-arrow": { char: "↙", file: "emoji/emoji-down-left-arrow.svg", tier: "extra" },
  "up-left-arrow": { char: "↖", file: "emoji/emoji-up-left-arrow.svg", tier: "extra" },
  "up-down-arrow": { char: "↕", file: "emoji/emoji-up-down-arrow.svg", tier: "extra" },
  "left-right-arrow": { char: "↔", file: "emoji/emoji-left-right-arrow.svg", tier: "extra" },
  "right-arrow-curving-left": { char: "↩", file: "emoji/emoji-right-arrow-curving-left.svg", tier: "extra" },
  "left-arrow-curving-right": { char: "↪", file: "emoji/emoji-left-arrow-curving-right.svg", tier: "extra" },
  "star-of-david": { char: "✡", file: "emoji/emoji-star-of-david.svg", tier: "extra" },
  "wheel-of-dharma": { char: "☸", file: "emoji/emoji-wheel-of-dharma.svg", tier: "extra" },
  "yin-yang": { char: "☯", file: "emoji/emoji-yin-yang.svg", tier: "native" },
  "latin-cross": { char: "✝", file: "emoji/emoji-latin-cross.svg", tier: "extra" },
  "orthodox-cross": { char: "☦", file: "emoji/emoji-orthodox-cross.svg", tier: "extra" },
  "star-and-crescent": { char: "☪", file: "emoji/emoji-star-and-crescent.svg", tier: "extra" },
  "peace-symbol": { char: "☮", file: "emoji/emoji-peace-symbol.svg", tier: "native" },
  "aries": { char: "♈", file: "emoji/emoji-aries.svg", tier: "extra" },
  "taurus": { char: "♉", file: "emoji/emoji-taurus.svg", tier: "extra" },
  "gemini": { char: "♊", file: "emoji/emoji-gemini.svg", tier: "extra" },
  "cancer": { char: "♋", file: "emoji/emoji-cancer.svg", tier: "extra" },
  "leo": { char: "♌", file: "emoji/emoji-leo.svg", tier: "extra" },
  "virgo": { char: "♍", file: "emoji/emoji-virgo.svg", tier: "extra" },
  "libra": { char: "♎", file: "emoji/emoji-libra.svg", tier: "extra" },
  "scorpio": { char: "♏", file: "emoji/emoji-scorpio.svg", tier: "extra" },
  "sagittarius": { char: "♐", file: "emoji/emoji-sagittarius.svg", tier: "extra" },
  "capricorn": { char: "♑", file: "emoji/emoji-capricorn.svg", tier: "extra" },
  "aquarius": { char: "♒", file: "emoji/emoji-aquarius.svg", tier: "extra" },
  "pisces": { char: "♓", file: "emoji/emoji-pisces.svg", tier: "extra" },
  "play-button": { char: "▶", file: "emoji/emoji-play-button.svg", tier: "extra" },
  "reverse-button": { char: "◀", file: "emoji/emoji-reverse-button.svg", tier: "extra" },
  "female-sign": { char: "♀", file: "emoji/emoji-female-sign.svg", tier: "native" },
  "male-sign": { char: "♂", file: "emoji/emoji-male-sign.svg", tier: "native" },
  "multiply": { char: "✖", file: "emoji/emoji-multiply.svg", tier: "extra" },
  "double-exclamation-mark": { char: "‼", file: "emoji/emoji-double-exclamation-mark.svg", tier: "extra" },
  "wavy-dash": { char: "〰", file: "emoji/emoji-wavy-dash.svg", tier: "text" },
  "check-box-with-check": { char: "☑", file: "emoji/emoji-check-box-with-check.svg", tier: "native" },
  "check-mark": { char: "✔", file: "emoji/emoji-check-mark.svg", tier: "native" },
  "eight-spoked-asterisk": { char: "✳", file: "emoji/emoji-eight-spoked-asterisk.svg", tier: "extra" },
  "eight-pointed-star": { char: "✴", file: "emoji/emoji-eight-pointed-star.svg", tier: "extra" },
  "sparkle": { char: "❇", file: "emoji/emoji-sparkle.svg", tier: "extra" },
  "copyright": { char: "©", file: "emoji/emoji-copyright.svg", tier: "extra" },
  "registered": { char: "®", file: "emoji/emoji-registered.svg", tier: "extra" },
  "trade-mark": { char: "™", file: "emoji/emoji-trade-mark.svg", tier: "extra" },
  "circled-m": { char: "Ⓜ", file: "emoji/emoji-circled-m.svg", tier: "extra" },
  "japanese-congratulations-button": { char: "㊗", file: "emoji/emoji-japanese-congratulations-button.svg", tier: "text" },
  "japanese-secret-button": { char: "㊙", file: "emoji/emoji-japanese-secret-button.svg", tier: "text" },
  "black-small-square": { char: "▪", file: "emoji/emoji-black-small-square.svg", tier: "extra" },
  "white-small-square": { char: "▫", file: "emoji/emoji-white-small-square.svg", tier: "extra" },
  "trigram-for-earth": { char: "☷", file: "emoji/emoji-trigram-for-earth.svg", tier: "extra" },
  "trigram-for-water": { char: "☵", file: "emoji/emoji-trigram-for-water.svg", tier: "extra" },
  "trigram-for-mountain": { char: "☶", file: "emoji/emoji-trigram-for-mountain.svg", tier: "extra" },
  "descending-node": { char: "☋", file: "emoji/emoji-descending-node.svg", tier: "extra" },
  "asterisk": { char: "*", file: "emoji/emoji-asterisk.svg", tier: "extra" },
  "conjunction": { char: "☌", file: "emoji/emoji-conjunction.svg", tier: "extra" },
  "black-chess-rook": { char: "♜", file: "emoji/emoji-black-chess-rook.svg", tier: "extra" },
  "white-chess-queen": { char: "♕", file: "emoji/emoji-white-chess-queen.svg", tier: "extra" },
  "white-heart-suit": { char: "♡", file: "emoji/emoji-white-heart-suit.svg", tier: "extra" },
  "beamed-sixteenth-notes": { char: "♬", file: "emoji/emoji-beamed-sixteenth-notes.svg", tier: "extra" },
  "black-left-pointing-index": { char: "☚", file: "emoji/emoji-black-left-pointing-index.svg", tier: "extra" },
  "music-natural-sign": { char: "♮", file: "emoji/emoji-music-natural-sign.svg", tier: "extra" },
  "black-chess-bishop": { char: "♝", file: "emoji/emoji-black-chess-bishop.svg", tier: "extra" },
  "sharp": { char: "♯", file: "emoji/emoji-sharp.svg", tier: "extra" },
  "trigram-for-wind": { char: "☴", file: "emoji/emoji-trigram-for-wind.svg", tier: "extra" },
  "flat": { char: "♭", file: "emoji/emoji-flat.svg", tier: "extra" },
  "saltire": { char: "☓", file: "emoji/emoji-saltire.svg", tier: "extra" },
  "black-right-pointing-index": { char: "☛", file: "emoji/emoji-black-right-pointing-index.svg", tier: "extra" },
  "hammer-and-sickle": { char: "☭", file: "emoji/emoji-hammer-and-sickle.svg", tier: "extra" },
  "digit-zero": { char: "0", file: "emoji/emoji-digit-zero.svg", tier: "extra" },
  "white-diamond-suit": { char: "♢", file: "emoji/emoji-white-diamond-suit.svg", tier: "extra" },
  "digit-three": { char: "3", file: "emoji/emoji-digit-three.svg", tier: "extra" },
  "upper-right-pencil": { char: "✐", file: "emoji/emoji-upper-right-pencil.svg", tier: "extra" },
  "white-chess-rook": { char: "♖", file: "emoji/emoji-white-chess-rook.svg", tier: "extra" },
  "thunderstorm": { char: "☈", file: "emoji/emoji-thunderstorm.svg", tier: "extra" },
  "ballot-box-with-x": { char: "☒", file: "emoji/emoji-ballot-box-with-x.svg", tier: "extra" },
  "black-star": { char: "★", file: "emoji/emoji-black-star.svg", tier: "extra" },
  "black-chess-king": { char: "♚", file: "emoji/emoji-black-chess-king.svg", tier: "extra" },
  "black-chess-queen": { char: "♛", file: "emoji/emoji-black-chess-queen.svg", tier: "extra" },
  "lower-right-pencil": { char: "✎", file: "emoji/emoji-lower-right-pencil.svg", tier: "extra" },
  "eighth-note": { char: "♪", file: "emoji/emoji-eighth-note.svg", tier: "extra" },
  "trigram-for-heaven": { char: "☰", file: "emoji/emoji-trigram-for-heaven.svg", tier: "extra" },
  "first-quarter-moon": { char: "☽", file: "emoji/emoji-first-quarter-moon.svg", tier: "extra" },
  "caution-sign": { char: "☡", file: "emoji/emoji-caution-sign.svg", tier: "extra" },
  "white-sun-with-rays": { char: "☼", file: "emoji/emoji-white-sun-with-rays.svg", tier: "extra" },
  "uranus": { char: "♅", file: "emoji/emoji-uranus.svg", tier: "extra" },
  "ballot-box": { char: "☐", file: "emoji/emoji-ballot-box.svg", tier: "extra" },
  "white-down-pointing-index": { char: "☟", file: "emoji/emoji-white-down-pointing-index.svg", tier: "extra" },
  "floral-heart": { char: "❦", file: "emoji/emoji-floral-heart.svg", tier: "extra" },
  "ascending-node": { char: "☊", file: "emoji/emoji-ascending-node.svg", tier: "extra" },
  "opposition": { char: "☍", file: "emoji/emoji-opposition.svg", tier: "extra" },
  "adi-shakti": { char: "☬", file: "emoji/emoji-adi-shakti.svg", tier: "extra" },
  "digit-seven": { char: "7", file: "emoji/emoji-digit-seven.svg", tier: "extra" },
  "white-club-suit": { char: "♧", file: "emoji/emoji-white-club-suit.svg", tier: "extra" },
  "farsi-symbol": { char: "☫", file: "emoji/emoji-farsi-symbol.svg", tier: "extra" },
  "trigram-for-lake": { char: "☱", file: "emoji/emoji-trigram-for-lake.svg", tier: "extra" },
  "last-quarter-moon": { char: "☾", file: "emoji/emoji-last-quarter-moon.svg", tier: "extra" },
  "caduceus": { char: "☤", file: "emoji/emoji-caduceus.svg", tier: "extra" },
  "rotated-floral-heart-bullet": { char: "❧", file: "emoji/emoji-rotated-floral-heart-bullet.svg", tier: "extra" },
  "digit-two": { char: "2", file: "emoji/emoji-digit-two.svg", tier: "extra" },
  "digit-eight": { char: "8", file: "emoji/emoji-digit-eight.svg", tier: "extra" },
  "saturn": { char: "♄", file: "emoji/emoji-saturn.svg", tier: "extra" },
  "earth": { char: "♁", file: "emoji/emoji-earth.svg", tier: "extra" },
  "digit-one": { char: "1", file: "emoji/emoji-digit-one.svg", tier: "extra" },
  "white-chess-king": { char: "♔", file: "emoji/emoji-white-chess-king.svg", tier: "extra" },
  "digit-four": { char: "4", file: "emoji/emoji-digit-four.svg", tier: "extra" },
  "rotated-heavy-black-heart-bullet": { char: "❥", file: "emoji/emoji-rotated-heavy-black-heart-bullet.svg", tier: "extra" },
  "ankh": { char: "☥", file: "emoji/emoji-ankh.svg", tier: "extra" },
  "black-smiling-face": { char: "☻", file: "emoji/emoji-black-smiling-face.svg", tier: "extra" },
  "digit-five": { char: "5", file: "emoji/emoji-digit-five.svg", tier: "extra" },
  "white-spade-suit": { char: "♤", file: "emoji/emoji-white-spade-suit.svg", tier: "extra" },
  "digit-six": { char: "6", file: "emoji/emoji-digit-six.svg", tier: "extra" },
  "black-chess-knight": { char: "♞", file: "emoji/emoji-black-chess-knight.svg", tier: "extra" },
  "neptune": { char: "♆", file: "emoji/emoji-neptune.svg", tier: "extra" },
  "hash-sign": { char: "#", file: "emoji/emoji-hash-sign.svg", tier: "extra" },
  "jupiter": { char: "♃", file: "emoji/emoji-jupiter.svg", tier: "extra" },
  "quarter-note": { char: "♩", file: "emoji/emoji-quarter-note.svg", tier: "extra" },
  "digit-nine": { char: "9", file: "emoji/emoji-digit-nine.svg", tier: "extra" },
  "lightning": { char: "☇", file: "emoji/emoji-lightning.svg", tier: "extra" },
  "white-right-pointing-index": { char: "☞", file: "emoji/emoji-white-right-pointing-index.svg", tier: "extra" },
  "beamed-eighth-notes": { char: "♫", file: "emoji/emoji-beamed-eighth-notes.svg", tier: "extra" },
  "white-telephone": { char: "☏", file: "emoji/emoji-white-telephone.svg", tier: "extra" },
  "white-chess-knight": { char: "♘", file: "emoji/emoji-white-chess-knight.svg", tier: "extra" },
  "chi-rho": { char: "☧", file: "emoji/emoji-chi-rho.svg", tier: "extra" },
  "sun-2": { char: "☉", file: "emoji/emoji-sun-2.svg", tier: "extra" },
  "pluto": { char: "♇", file: "emoji/emoji-pluto.svg", tier: "extra" },
  "cross-of-jerusalem": { char: "☩", file: "emoji/emoji-cross-of-jerusalem.svg", tier: "extra" },
  "white-chess-pawn": { char: "♙", file: "emoji/emoji-white-chess-pawn.svg", tier: "extra" },
  "white-left-pointing-index": { char: "☜", file: "emoji/emoji-white-left-pointing-index.svg", tier: "extra" },
  "trigram-for-fire": { char: "☲", file: "emoji/emoji-trigram-for-fire.svg", tier: "extra" },
  "cross-of-lorraine": { char: "☨", file: "emoji/emoji-cross-of-lorraine.svg", tier: "extra" },
  "white-chess-bishop": { char: "♗", file: "emoji/emoji-white-chess-bishop.svg", tier: "extra" },
  "trigram-for-thunder": { char: "☳", file: "emoji/emoji-trigram-for-thunder.svg", tier: "extra" },
  "umbrella-with-rain-drops": { char: "☔", file: "emoji/emoji-umbrella-with-rain-drops.svg", tier: "native" },
  "anchor": { char: "⚓", file: "emoji/emoji-anchor.svg", tier: "native" },
  "crossed-swords": { char: "⚔", file: "emoji/emoji-crossed-swords.svg", tier: "native" },
  "alembic": { char: "⚗", file: "emoji/emoji-alembic.svg", tier: "native" },
  "warning": { char: "⚠", file: "emoji/emoji-warning.svg", tier: "native" },
  "high-voltage": { char: "⚡", file: "emoji/emoji-high-voltage.svg", tier: "native" },
  "snowman-without-snow": { char: "⛄", file: "emoji/emoji-snowman-without-snow.svg", tier: "native" },
  "cloud-with-lightning-and-rain": { char: "⛈", file: "emoji/emoji-cloud-with-lightning-and-rain.svg", tier: "native" },
  "pick": { char: "⛏", file: "emoji/emoji-pick.svg", tier: "native" },
  "fire": { char: "🔥", file: "emoji/emoji-fire.svg", tier: "native" },
  "water-wave": { char: "🌊", file: "emoji/emoji-water-wave.svg", tier: "native" },
  "dagger": { char: "🗡", file: "emoji/emoji-dagger.svg", tier: "native" },
  "bow-and-arrow": { char: "🏹", file: "emoji/emoji-bow-and-arrow.svg", tier: "native" },
  "axe": { char: "🪓", file: "emoji/emoji-axe.svg", tier: "native" },
  "trident": { char: "🔱", file: "emoji/emoji-trident.svg", tier: "native" },
  "fishing-pole": { char: "🎣", file: "emoji/emoji-fishing-pole.svg", tier: "native" },
  "test-tube": { char: "🧪", file: "emoji/emoji-test-tube.svg", tier: "native" },
  "meat-on-bone": { char: "🍖", file: "emoji/emoji-meat-on-bone.svg", tier: "native" },
  "bucket": { char: "🪣", file: "emoji/emoji-bucket.svg", tier: "native" },
  "bell": { char: "🔔", file: "emoji/emoji-bell.svg", tier: "native" },
  "hourglass-done-2": { char: "⏳", file: "emoji/emoji-hourglass-done-2.svg", tier: "native" },
};

export const MC_EMOJI_COUNT = 186;

/** Все эмодзи, которые Minecraft рисует сам (Mojangles, с 1.20.2). */
export const MC_EMOJI_NATIVE: McEmoji[] = Object.values(MC_EMOJI).filter((e) => e.tier === "native");

/** Найти запись по символу. */
export function findMcEmoji(char: string): McEmoji | undefined {
return Object.values(MC_EMOJI).find((e) => e.char === char);
}
