ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS deaths BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS blocks_mined BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS distance_cm BIGINT NOT NULL DEFAULT 0;
