# Squid: CONNECT-прокси только для доменов которые нужны NeoForge installer
# и лаунчеру. Всё остальное запрещено.

acl allowed_sites dstdomain maven.neoforged.net libraries.minecraft.net piston-meta.mojang.com piston-data.mojang.com resources.download.minecraft.net api.adoptium.net github.com api.github.com objects.githubusercontent.com auth.zeragorn.xyz admin.zeragorn.xyz assets.zeragorn.xyz sessionserver.mojang.com api.minecraftservices.com textures.minecraft.net www.minecraft.net mojang.com authlib-injector.yushi.moe

http_access allow allowed_sites
http_access deny all

http_port 3128

# Не пишем логи доступа (лишний шум).
access_log none
